INSERT INTO riddles(text, answer, level) VALUES
("A man is trapped in a room. The room has only two possible exits: two doors. Through the first door there is a room constructed from magnifying glass. The blazing hot sun instantly fries anything or anyone that enters. Through the second door there is a fire-breathing dragon. How does the man escape?", "He waits until night time and then goes through the first door.", 3),
("A woman is sitting in her hotel room when there is a knock at the door. She opened the door to see a man whom she had never seen before. He said 'oh I'm sorry, I have made a mistake, I thought this was my room.' He then went down the corridor and in the elevator. The woman went back into her room and phoned security. What made the woman so suspicious of the man?", "You don’t knock on your own hotel room door and the man did.", 5),
("Feed me and I live, yet give me a drink and I die", "fire", 1),
("A king has no sons, no daughters, and no queen. For this reason he must decide who will take the throne after he dies. To do this he decides that he will give all of the children of the kingdom a single seed. Whichever child has the largest, most beautiful plant will earn the throne; this being a metaphor for the kingdom.At the end of the contest all of the children came to the palace with their enormous and beautiful plants in hand. After he looks at all of the children's pots, he finally decides that the little girl with an empty pot will be the next Queen. Why did he choose this little girl over all of the other children with their beautiful plants?", "The king gave them all fake seeds and the little girl was the only honest child who didn't switch seeds", 4),
("An old man wanted to leave all of his money to one of his three sons, but he didn't know which one he should give it to. He gave each of them a few coins and told them to buy something that would be able to fill their living room. The first man bought straw, but there was not enough to fill the room. The second bought some sticks, but they still did not fill the room. The third man bought two things that filled the room, so he obtained his father's fortune. What were the two things that the man bought?", "The wise son bought a candle and a box of matches. After lighting the candle, the light filled the entire room", 2),
("What 4-letter word can be written forward, backward or upside down, and can still be read from left to right?", "NOON", 3),
("Mr. Smith has 4 daughters. Each of his daughters has a brother. How many children does Mr. Smith have?", "He has 5 children, all of the daughters have the same 1 brother", 2),
("A man wants to enter an exclusive club, but he doesn't know the password. Another man walks to the door and the doorman says 12, the man says 6, and is let in. Another man walks up and the doorman says 6, the man says 3, and is let in. Thinking he had heard enough, he walks up to the door and the doorman says 10, he says 5, and he isn't let in. What should he have said?", "Three. He should have said how many letters were in the number he said.", 5),
("A thief enters a shop and threatens the clerk, forcing him to open the safe. The clerk says, 'The code for the safe is different every day, and if you hurt me you'll never get the code'. But the thief manages to guess the code on his own How did he do it?", "The code is 'different'", 4),
("16, 06, 68, 88, ?, 98 What is the ‘?’", "78", 1),
("What flies when it’s born, lies when it’s alive, and runs when it’s dead?", "A Snowflake", 3),
("I am a mother and a father, but have never given birth. I’m rarely still, but I never wander. What am I?", "Tree", 3),
("What can’t be burned in a fire nor drowned in water?", "ice", 2);